### PR TITLE
RTM and removed targeting framework 4.6

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by andreasohlund** [comment]
@fhalim can you upload the stable 2.0.0? (or make me an owner so I can do it)

@SimonCropp I wonder if we should create a `ParticularLabs` nuget account?

**Comment by SimonCropp** [comment]
@andreasohlund not sure? the nuget and the repo can have their own license. and i know "but people can ignore the license" but based on that they could equally ignore the owner. so i would just say a diff license. that is if u dont want to run it under the standard license

**Comment by andreasohlund** [comment]
so you're saying to push the nuget to our account?

**Comment by SimonCropp** [comment]
i think it would be fine to add particular to the nuget permissions. so still give @fhalim credit moving forward

**Comment by andreasohlund** [comment]
I've now accepted the invite, particular is now the co-owner of the package

**Comment by fhalim** [comment]
I've added the `nservicebus` account as an owner of the package.

**Pull request merged**
